<!DOCTYPE html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StudyFY | Início</title>
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<style>body{margin:0;font-family:Poppins,sans-serif;color:#464649}.nav{background:#464649;padding:16px 0}.nav a{color:#fff;text-decoration:none}.brand{font-size:25px;font-weight:700}.brand span{font-weight:400}.hero{background:#7A7A7C;color:#fff;padding:100px 0}.hero h1{font-size:58px;font-weight:700}.hero{position:relative;overflow:hidden}.hero .container{position:relative;z-index:1}.feature-logo{display:block;width:260px;max-width:80%;height:auto;margin:-60px auto -50px}.books{position:absolute;inset:0;z-index:0;pointer-events:none}.book{position:absolute;top:-60px;color:#727274;opacity:1;animation:fall linear infinite}.book svg{width:100%;height:auto;display:block;fill:currentColor}@keyframes fall{from{top:-70px;transform:rotate(var(--r0))}to{top:105%;transform:rotate(var(--r1))}}@media (prefers-reduced-motion:reduce){.book{animation:none;top:var(--y)}}.btnsf{background:#464649;color:#fff;border-radius:25px;padding:12px 25px}.btnsf:hover{color:#fff;background:#333}.feature{padding:70px 0}.cardx{border-radius:16px;box-shadow:0 5px 20px #0001;padding:30px;height:100%;background:#fff}</style></head>
<body><nav class="nav"><div class="container d-flex justify-content-between align-items-center"><a class="brand" href="{{ url('/') }}"><span>Study</span>FY</a><div><a class="mr-4" href="{{ route('login') }}">Login</a><a href="{{ route('register') }}">Cadastre-se</a></div></div></nav>
<section class="hero">
<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs><symbol id="bk" viewBox="0 0 40 52"><path fill-rule="evenodd" d="M4 0h32a4 4 0 0 1 4 4v44a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4a4 4 0 0 1 4-4zM7 0v52h2V0zM14 10h20v5H14zM14 19h14v3H14z"/></symbol></defs></svg>
<div class="books" aria-hidden="true">@php mt_srand(7); @endphp @for($i=0;$i<22;$i++)@php $w=mt_rand(16,30); $d=mt_rand(14,26); $r0=mt_rand(-40,40); $r1=$r0+mt_rand(-120,120); $y=mt_rand(0,90); @endphp<div class="book" style="left:{{ mt_rand(0,96) }}%;width:{{ $w }}px;animation-duration:{{ $d }}s;animation-delay:-{{ mt_rand(0,$d) }}s;--r0:{{ $r0 }}deg;--r1:{{ $r1 }}deg;--y:{{ $y }}%"><svg viewBox="0 0 40 52"><use href="#bk"/></svg></div>@endfor</div>
<div class="container"><div class="col-lg-8 px-0"><p>PLANEJE, ESTUDE, EVOLUA</p><h1>Seu estudo mais organizado.</h1><p class="lead">Cadastre matérias, organize conteúdos, acompanhe seu progresso e mantenha o foco com o cronômetro.</p><a class="btn btnsf" href="{{ route('register') }}">Começar agora</a></div></div></section>
<section class="feature"><div class="container"><img class="feature-logo" src="{{ asset('images/logo.png') }}" alt="StudyFY"><h2 class="text-center mb-5">Tudo em um só lugar</h2><div class="row"><div class="col-md-4 mb-4"><div class="cardx"><h4>Matérias</h4><p>Crie, edite, pesquise e exclua suas disciplinas.</p></div></div><div class="col-md-4 mb-4"><div class="cardx"><h4>Conteúdos</h4><p>Associe conteúdos às matérias e marque o que já concluiu.</p></div></div><div class="col-md-4 mb-4"><div class="cardx"><h4>Foco</h4><p>Use o cronômetro para estudar com sessões de concentração.</p></div></div></div></div></section>
<footer style="background:#7A7A7C;color:#fff;padding:25px;text-align:center">StudyFY | Estudo para você · {{ date('Y') }}</footer></body></html>